import { jsx as _jsx, jsxs as _jsxs } from "hono/jsx/jsx-runtime";
import { BasePage } from "./layout";
export function LandingPage(boards) {
    return _jsx("div", { id: "landingPage", style: "display: contents", children: _jsx("div", { class: "min-h-screen bg-base-200", children: _jsxs("main", { id: "index", class: "w-full max-w-4xl mx-auto p-8 space-y-10 rounded-[2.5rem] bg-base-100 dark:bg-base-200 shadow-xl", children: [_jsxs("header", { class: "text-center space-y-3", children: [_jsx("p", { class: "text-sm uppercase tracking-wide text-secondary", children: "Your workspace" }), _jsx("h1", { class: "text-4xl font-black text-primary", children: "Boards" }), _jsx("p", { class: "text-base text-base-content/60", children: "Choose to jump into your Kanban flow." })] }), _jsx("div", { class: "flex justify-end", children: _jsx("button", { class: "btn btn-primary", onclick: "addBoardModal.showModal()", children: "Add Board" }) }), _jsx(BoardsList, { boards: boards }), _jsx(AddBoardModal, {})] }) }) });
}
export function IndexPage({ boards }) {
    return (_jsxs(BasePage, { title: "Kanban Boards", children: [_jsx("div", { id: 'init-sse', "data-init": '@get("/sse")' }), LandingPage(boards)] }));
}
function BoardsList({ boards }) {
    return (_jsx("section", { id: "boards-list", class: "grid gap-8 md:grid-cols-2", children: boards.length === 0 ? (_jsx("div", { class: "card bg-base-200 dark:bg-base-300 shadow-xl", children: _jsxs("div", { class: "card-body items-center text-center", children: [_jsx("h2", { class: "card-title text-secondary", children: "No boards yet" }), _jsx("p", { class: "text-base-content/60", children: "Create your first board to get started." })] }) })) : (boards.map((board) => _jsx(BoardCard, { board: board }))) }));
}
function BoardCard({ board }) {
    return (_jsx("a", { href: `/board/${board.id}`, class: "card bg-base-200 dark:bg-base-300 shadow-xl hover:shadow-2xl hover:scale-[1.02] transition-all", children: _jsxs("div", { class: "card-body", children: [_jsx("h2", { class: "card-title text-primary", children: board.title }), board.description ? (_jsx("p", { class: "text-sm text-base-content/60", children: board.description })) : (_jsx("p", { class: "badge badge-secondary badge-outline w-fit shadow", children: "No description" })), _jsx("div", { class: "card-actions justify-end", children: _jsx("span", { class: "btn btn-secondary btn-sm shadow-lg", children: "Open board" }) })] }) }));
}
function AddBoardModal() {
    return (_jsx("dialog", { id: "addBoardModal", class: "modal", children: _jsxs("div", { class: "modal-box bg-base-200 dark:bg-base-300", children: [_jsx("button", { type: "button", class: "btn btn-sm btn-circle btn-ghost absolute right-2 top-2", onclick: "addBoardModal.close()", children: "\u2715" }), _jsxs("form", { method: "post", "data-on:submit": "@post('/board', {contentType: 'form'}) && addBoardModal.close();", children: [_jsx("h3", { class: "font-bold text-lg mb-4", children: "Add New Board" }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "board-title", children: _jsx("span", { class: "label-text", children: "Title" }) }), _jsx("input", { id: "board-title", name: "title", type: "text", class: "input input-bordered w-full", placeholder: "Enter board title", required: true, "data-bind": "title" })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "board-description", children: _jsx("span", { class: "label-text", children: "Description" }) }), _jsx("textarea", { id: "board-description", name: "description", class: "textarea textarea-bordered h-24 w-full", placeholder: "Enter board description (optional)", "data-bind": "description" })] }), _jsxs("div", { class: "modal-action", children: [_jsx("button", { type: "button", class: "btn btn-ghost", onclick: "addBoardModal.close()", children: "Cancel" }), _jsx("button", { type: "submit", class: "btn btn-primary", children: "Add Board" })] })] })] }) }));
}
