import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "hono/jsx/jsx-runtime";
export function AddCardModal({ boardId, users, tags, }) {
    return (_jsxs(_Fragment, { children: [_jsx("dialog", { id: "addCardModal", class: "modal", children: _jsxs("div", { class: "modal-box bg-base-200 dark:bg-base-300", children: [_jsx("button", { type: "button", class: "btn btn-sm btn-circle btn-ghost absolute right-2 top-2", onclick: "addCardModal.close()", children: "\u2715" }), _jsxs("form", { method: "post", "data-on:submit": `@post('/board/${boardId}/card', {contentType: 'form'}); addCardModal.close()`, children: [_jsx("h3", { class: "font-bold text-lg mb-4", children: "Add New Card" }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "card-title", children: _jsx("span", { class: "label-text", children: "Title" }) }), _jsx("input", { id: "card-title", name: "title", type: "text", class: "input input-bordered w-full", placeholder: "Enter card title", required: true })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "card-description", children: _jsx("span", { class: "label-text", children: "Description" }) }), _jsx("textarea", { id: "card-description", name: "description", class: "textarea textarea-bordered h-24 w-full", placeholder: "Enter card description (optional)" })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "card-assignee", children: _jsx("span", { class: "label-text", children: "Assignee" }) }), _jsxs("select", { id: "card-assignee", name: "assigneeId", class: "select select-bordered w-full", children: [_jsx("option", { value: "", children: "Unassigned" }), users.map((user) => (_jsx("option", { value: user.id, children: user.name })))] })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("div", { class: "label", children: _jsx("span", { class: "label-text", children: "Tags" }) }), _jsx("div", { class: "flex flex-wrap gap-2 p-4 border border-base-300 rounded-lg", children: tags.map((tag) => (_jsxs("label", { class: "tag-checkbox-label badge border-2 font-semibold cursor-pointer transition-all hover:scale-105", style: `--tag-color: ${tag.color}; color: ${tag.color}; border-color: ${tag.color};`, children: [_jsx("input", { type: "checkbox", name: "tagIds", value: tag.id, class: "hidden" }), _jsx("span", { children: tag.name })] }))) })] }), _jsxs("div", { class: "modal-action", children: [_jsx("button", { type: "button", class: "btn btn-ghost", onclick: "addCardModal.close()", children: "Cancel" }), _jsx("button", { type: "submit", class: "btn btn-primary", children: "Add Card" })] })] })] }) }), _jsx("style", { dangerouslySetInnerHTML: {
                    __html: `
        .tag-checkbox-label:has(input:checked) {
          background-color: var(--tag-color) !important;
          color: white !important;
        }
      `,
                } })] }));
}
export function EditCardModal({ boardId, users, tags, }) {
    return (_jsx("dialog", { id: "editCardModal", class: "modal", children: _jsxs("div", { class: "modal-box bg-base-200 dark:bg-base-300", children: [_jsx("button", { type: "button", class: "btn btn-sm btn-circle btn-ghost absolute right-2 top-2", onclick: "editCardModal.close()", children: "\u2715" }), _jsx("h3", { class: "font-bold text-lg mb-4", children: "Edit Card" }), _jsxs("form", { method: "post", "data-on:submit": `@post('/board/${boardId}/card/' + $cardId, {contentType: 'form'}); editCardModal.close()`, children: [_jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "edit-card-title", children: _jsx("span", { class: "label-text", children: "Title" }) }), _jsx("input", { id: "edit-card-title", name: "title", type: "text", class: "input input-bordered w-full", placeholder: "Enter card title", "data-bind": "editTitle", required: true })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "edit-card-description", children: _jsx("span", { class: "label-text", children: "Description" }) }), _jsx("textarea", { id: "edit-card-description", name: "description", class: "textarea textarea-bordered h-24 w-full", placeholder: "Enter card description (optional)", "data-bind": "editDescription" })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "edit-card-assignee", children: _jsx("span", { class: "label-text", children: "Assignee" }) }), _jsxs("select", { id: "edit-card-assignee", name: "assigneeId", class: "select select-bordered w-full", "data-bind": "editAssigneeId", children: [_jsx("option", { value: "", children: "Unassigned" }), users.map((user) => (_jsx("option", { value: user.id, children: user.name })))] })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("div", { class: "label", children: _jsx("span", { class: "label-text", children: "Tags" }) }), _jsx("div", { class: "flex flex-wrap gap-2 p-4 border border-base-300 rounded-lg", children: tags.map((tag) => (_jsxs("label", { class: "tag-checkbox-label badge border-2 font-semibold cursor-pointer transition-all hover:scale-105", style: `--tag-color: ${tag.color}; color: ${tag.color}; border-color: ${tag.color};`, children: [_jsx("input", { type: "checkbox", name: "tagIds", value: tag.id, class: "hidden" }), _jsx("span", { children: tag.name })] }))) })] }), _jsxs("div", { class: "modal-action justify-between", children: [_jsx("button", { type: "button", class: "btn btn-error", "data-on:click": `if(confirm('Are you sure you want to delete this card?')) { @delete('/board/${boardId}/card/' + $cardId); editCardModal.close() }`, children: "Delete Card" }), _jsxs("div", { class: "flex gap-2", children: [_jsx("button", { type: "button", class: "btn btn-ghost", onclick: "editCardModal.close()", children: "Cancel" }), _jsx("button", { type: "submit", class: "btn btn-primary", children: "Save Changes" })] })] })] })] }) }));
}
export function AddCommentModal({ boardId, users, }) {
    return (_jsx("dialog", { id: "addCommentModal", class: "modal", children: _jsxs("div", { class: "modal-box bg-base-200 dark:bg-base-300 max-w-2xl", children: [_jsx("button", { type: "button", class: "btn btn-sm btn-circle btn-ghost absolute right-2 top-2", onclick: "addCommentModal.close()", children: "\u2715" }), _jsx("h3", { class: "font-bold text-lg mb-4", children: "Add Comment" }), _jsxs("form", { method: "post", "data-on:submit": `@post('/board/${boardId}/card/' + $cardId + '/comment', {contentType: 'form'}); addCommentModal.close()`, children: [_jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "comment-user", children: _jsx("span", { class: "label-text", children: "Comment as" }) }), _jsx("select", { id: "comment-user", name: "userId", class: "select select-bordered w-full", required: true, children: users.map((user) => (_jsx("option", { value: user.id, children: user.name }))) })] }), _jsxs("div", { class: "form-control w-full mb-4", children: [_jsx("label", { class: "label", for: "comment-text", children: _jsx("span", { class: "label-text", children: "Your comment" }) }), _jsx("textarea", { id: "comment-text", name: "text", class: "textarea textarea-bordered h-24 w-full", placeholder: "Write your comment...", required: true })] }), _jsxs("div", { class: "modal-action", children: [_jsx("button", { type: "button", class: "btn btn-ghost", onclick: "addCommentModal.close()", children: "Cancel" }), _jsx("button", { type: "submit", class: "btn btn-primary", children: "Add Comment" })] })] })] }) }));
}
